[package]
name = "hilbert_transform"
description = "An implementation of Hilbert Transformation like Matlab/Octave hilbert function"
version = "0.1.1"
edition = "2021"
license = "MIT"
repository = "https://github.com/lcscosta/hilbert_transform_rs"
keywords = ["signals", "hilbert", "transform", "demodulation"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustfft = "6.1.0"
